# This GitHub Actions workflow runs Cypress tests
# whenever code is pushed to the repository.

# Name of the workflow
name: Firefox specific tests

# Trigger for the workflow (runs on every push to the repository)
on: push

jobs:
  # Job to run Cypress tests for the login functionality
  login-run:
    # Specifies the runner environment for the job
    runs-on: ubuntu-22.04

    steps:
      # Checks out the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Runs Cypress tests for the login functionality on the Electron browser
      - name: login running on Electron browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:login

      # Generates and uploads a Mochawesome HTML report for the login tests
      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Login
          path: cypress/reports/html

  # Job to run Cypress tests for the add-to-cart functionality
  add-to-cart-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Runs Cypress tests for the add-to-cart functionality on the Firefox browser
      - name: addToCart running on Firefox browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:addToCart

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - AddToCart
          path: cypress/reports/html

  # Job to run Cypress tests for the registration functionality
  register-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Runs Cypress tests for the registration functionality on the Chrome browser
      - name: register running on Chrome browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:register

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Registeration
          path: cypress/reports/html

  # Commented out section for Slack notification
  # slackNotification:
  #   name: Slack Notification
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Slack Notification
  #       if: always()
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
  #         SLACK_ICON: https://github.com/rtCamp.png?size=48
  #         SLACK_MESSAGE: "Test Automation Report - https://github.com/ashutosh1556/WebAutomationUsingCypress/actions/runs/${{github.run_id}}"
  #         SLACK_TITLE: Cypress Web Test
  #         SLACK_USERNAME: Automation Bot
