# This GitHub Actions workflow runs Cypress tests
# whenever code is pushed to the repository.

name: Firefox specific tests
on: push

jobs:
  login-run:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: login running on Electron browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:login

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Login
          path: cypress/reports/html

  add-to-cart-run:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies, cache them and run Cypress tests
      # with the command 'npm run cypress:addToCart' in Firefox browser configured in package.json
      - name: addToCart running on Firefox browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:addToCart

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - AddToCart
          path: cypress/reports/html

  register-run:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies, cache them and run Cypress tests
      # with the command 'npm run cypress:addToCart' in Chrome browser configured in package.json
      - name: register running on Chrome browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:register

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Registeration
          path: cypress/reports/html

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Test Automation Report - https://github.com/ashutosh1556/WebAutomationUsingCypress/actions/runs/${{github.run_id}}"
          SLACK_TITLE: Cypress Web Test
          SLACK_USERNAME: Automation Bot
