# This GitHub Actions workflow runs Cypress tests
# whenever code is pushed to the repository.

name: Firefox specific tests
on: push

jobs:
  add-to-cart-run:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies, cache them and run Cypress tests
      # with the command 'npm run cypress:addToCart' in Firefox browser configured in package.json
      - name: addToCart running on Firefox browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:addToCart

      - name: login running on Electron browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:login

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Login and AddToCart
          path: cypress/reports/html

  register-run:
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies, cache them and run Cypress tests
      # with the command 'npm run cypress:addToCart' in Chrome browser configured in package.json
      - name: register running on Chrome browser
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:register

      - name: Generating Mochawesome Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: HTML Report - Registeration
          path: cypress/reports/html
